http:
  path: localhost
  port: 8080
database:
  driver: postgres
  host: localhost
  port: 5432
  user: postgres
  password: password
  dbname: homestay_db
  sslmode: disable
storage:
  cloudName: ddhsgiwcv
  apiKey: 584168378272983
  apiSecret: VSBpeP9AKFEzssd3BCvxhc6tyoI
